### ISSUE TITLE
Add [linktext](URL) Markdown option

### ISSUE THREAD

**Issue by schnps** [djl/copy-tab-info#1]
Saw your [post](https://www.reddit.com/r/firefox/comments/nh9dyw/any_way_to_use_the_copypaste_urltitle_feature_of/) on Reddit. 

"Copy URL/Title as markdown" doesn't work for me in Obsidian Markdown because the plugin copies as  `[URL](link text)` Markdown standard seems to be `[linktext](URL)` -- which is the format I want it in. Can you add another option to do it as `[linktext](URL)` ?

**Comment by djl** [comment]
Hey! That's not my reddit post but you definitely did find a bug. Not sure how I managed to do that.

Fixed in 924f98e. Thanks!
